# Generated by Django 3.2.4 on 2021-07-01 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del Edificio')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección del Edificio')),
                ('ciudad', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del departamento')),
                ('costo_dept', models.IntegerField(verbose_name='Costo del Departamento')),
                ('num_cuartos', models.IntegerField(verbose_name='Número Cuartos')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elEdificio', to='alquiler.edificio')),
            ],
        ),
    ]
