# Generated by Django 3.2.4 on 2021-07-05 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='alquiler.edificio'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Propietario'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre del Propietario'),
        ),
    ]
